name: PR validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  servoy-pr-validation:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/reusable-servoy-ci.yml
    with:
      project_name: servoy_test
      unit_test_solution: servoy_unit_tests
      enable_unit_tests: true
      servoy_assets_repo: ${{ vars.SERVOY_ASSETS_REPO }}
      artifact_name: pr-validation-logs
    secrets:
      servoy_asset_token: ${{ secrets.SERVOY_ASSET_TOKEN }}
