name: Servoy Integration Test

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - "feature/**"
  workflow_dispatch:
    inputs:
      repo_branch:
        description: "Branch of the Servoy project to test"
        required: false
        default: "main"

permissions:
  contents: read

jobs:
  servoy-test:
    uses: ./.github/workflows/reusable-run-tests.yml
    with:
      project_name: ${{ vars.SERVOY_PROJECT_NAME }}
      servoy_version: ${{ vars.SERVOY_VERSION }}
      servoy_assets_repo: ${{ vars.SERVOY_ASSETS_REPO }}
      run_unit_tests: ${{ vars.SERVOY_RUN_UNIT_TESTS == 'true' }}
      unit_test_solution: ${{ vars.SERVOY_UNIT_TEST_SOLUTION || 'servoy_unit_tests' }}
      repository_db_user: ${{ vars.CI_REPOSITORY_DB_USER || 'repository_user' }}
      app_db_1_server_name: ${{ vars.CI_APP_DB_1_SERVER_NAME || 'appdb' }}
      app_db_1_name: ${{ vars.CI_APP_DB_1_NAME || 'appdb' }}
      app_db_1_user: ${{ vars.CI_APP_DB_1_USER || 'appuser' }}
    secrets:
      servoy_asset_token: ${{ secrets.SERVOY_ASSET_TOKEN }}
      repository_db_password: ${{ secrets.CI_REPOSITORY_DB_PASSWORD }}
      app_db_1_password: ${{ secrets.CI_APP_DB_1_PASSWORD }}
